name: Deploy to Heroku

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4

      - name: Install dependencies
        run: |
          pip install -r requirements.pip
          pip install gunicorn

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: a2svhackathon
        run: |
          echo "machine api.heroku.com login $HEROKU_API_KEY" > ~/.netrc
          echo "machine git.heroku.com login $HEROKU_API_KEY" >> ~/.netrc
          git remote add heroku https://git.heroku.com/$HEROKU_APP_NAME.git
          git push heroku main:main
